-- KSO Creative / Supabase setup
-- Run this once in Supabase SQL Editor after creating your new project.

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text,
  category text check (category in ('web','video')),
  description text,
  media_url text,
  media_type text check (media_type in ('image','video') or media_type is null),
  media_path text,
  url text,
  role text,
  challenge text,
  solution text,
  results text,
  tools text,
  status text not null default 'published' check (status in ('published','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.projects enable row level security;

drop policy if exists "Public can view published projects" on public.projects;
create policy "Public can view published projects"
on public.projects for select
using (status = 'published');

drop policy if exists "Authenticated admins can insert projects" on public.projects;
create policy "Authenticated admins can insert projects"
on public.projects for insert to authenticated
with check (true);

drop policy if exists "Authenticated admins can update projects" on public.projects;
create policy "Authenticated admins can update projects"
on public.projects for update to authenticated
using (true) with check (true);

drop policy if exists "Authenticated admins can delete projects" on public.projects;
create policy "Authenticated admins can delete projects"
on public.projects for delete to authenticated
using (true);

insert into storage.buckets (id, name, public)
values ('project-media', 'project-media', true)
on conflict (id) do nothing;

drop policy if exists "Public can view project media" on storage.objects;
create policy "Public can view project media"
on storage.objects for select
using (bucket_id = 'project-media');

drop policy if exists "Authenticated admins can upload project media" on storage.objects;
create policy "Authenticated admins can upload project media"
on storage.objects for insert to authenticated
with check (bucket_id = 'project-media');

drop policy if exists "Authenticated admins can update project media" on storage.objects;
create policy "Authenticated admins can update project media"
on storage.objects for update to authenticated
using (bucket_id = 'project-media') with check (bucket_id = 'project-media');

drop policy if exists "Authenticated admins can delete project media" on storage.objects;
create policy "Authenticated admins can delete project media"
on storage.objects for delete to authenticated
using (bucket_id = 'project-media');
